import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:corsHeaders});
const basicAuth=(u:string,p:string)=>"Basic "+btoa(`${u}:${p}`);
const ln=(e:Element)=>e.localName||e.nodeName.split(":").pop()||"";
const all=(r:Document|Element,n:string)=>Array.from(r.getElementsByTagName("*")).filter(e=>ln(e)===n);
const first=(r:Element,n:string)=>{for(const e of Array.from(r.getElementsByTagName("*")))if(ln(e)===n)return e.textContent?.trim()||null;return null};
const abs=(b:string,h:string)=>new URL(h,b).toString();
class AppleError extends Error{status:number;constructor(status:number,message:string){super(message);this.status=status}}
async function caldav(url:string,method:string,auth:string,body?:string,depth?:string){const h:Record<string,string>={Authorization:auth,Accept:"application/xml, text/xml, text/calendar, */*"};if(depth!==undefined)h.Depth=depth;if(body)h["Content-Type"]="application/xml; charset=utf-8";const r=await fetch(url,{method,headers:h,body});const t=await r.text();if(!r.ok){console.error("iCloud CalDAV upstream",method,r.status,t.slice(0,1000));if(r.status===401||r.status===403)throw new AppleError(401,"Apple rejected the credentials. Use your Apple Account email and an app-specific password.");throw new AppleError(502,`Apple Calendar returned HTTP ${r.status}.`)}return t}
function parseDate(v?:string){if(!v)return null;const x=v.trim().split(":").pop()!;if(/^\d{8}$/.test(x))return{date:`${x.slice(0,4)}-${x.slice(4,6)}-${x.slice(6,8)}`,time:null};const m=x.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})/);return m?{date:`${m[1]}-${m[2]}-${m[3]}`,time:`${m[4]}:${m[5]}`}:null}
const un=(v:string)=>v.replace(/\\n/gi,"\n").replace(/\\,/g,",").replace(/\\;/g,";").replace(/\\\\/g,"\\").trim();
function parseIcs(ics:string){const out:any[]=[];let c:any=null;for(const line of ics.replace(/\r?\n[ \t]/g,"").split(/\r?\n/)){if(line==="BEGIN:VEVENT"){c={};continue}if(line==="END:VEVENT"){const s=parseDate(c?.DTSTART),e=parseDate(c?.DTEND);if(s)out.push({title:c.SUMMARY||"Imported calendar job",description:c.DESCRIPTION||"",location:c.LOCATION||"",date:s.date,time:s.time,endDate:e?.date||null,endTime:e?.time||null});c=null;continue}if(!c)continue;for(const k of ["SUMMARY","DESCRIPTION","LOCATION","DTSTART","DTEND"])if(line.startsWith(k+":")||line.startsWith(k+";")){c[k]=un(line.slice(line.indexOf(":")+1));break}}return out}
async function listCalendars(auth:string){const root="https://caldav.icloud.com/.well-known/caldav";const principalXml=await caldav(root,"PROPFIND",auth,`<?xml version="1.0"?><d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal/><d:principal-URL/></d:prop></d:propfind>`,`0`);const doc=new DOMParser().parseFromString(principalXml,"application/xml");const ph=all(doc,"response").map(x=>first(x,"href")).find(Boolean);if(!ph)throw new AppleError(502,"Apple did not return a calendar principal.");const pu=abs(root,ph);const homeXml=await caldav(pu,"PROPFIND",auth,`<?xml version="1.0"?><d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav"><d:prop><c:calendar-home-set/></d:prop></d:propfind>`,`0`);const homeDoc=new DOMParser().parseFromString(homeXml,"application/xml");const hh=first(homeDoc.documentElement,"href");if(!hh)throw new AppleError(502,"Apple did not return a calendar home.");const hu=abs(pu,hh);const calendarsXml=await caldav(hu,"PROPFIND",auth,`<?xml version="1.0"?><d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav"><d:prop><d:displayname/><d:resourcetype/></d:prop></d:propfind>`,`1`);const calendarsDoc=new DOMParser().parseFromString(calendarsXml,"application/xml");return all(calendarsDoc,"response").map(x=>{const u=first(x,"href"),isCal=Array.from(x.getElementsByTagName("*")).some(e=>ln(e)==="calendar");return u&&isCal?{id:abs(hu,u),name:first(x,"displayname")||"Apple Calendar"}:null}).filter(Boolean)}
async function events(url:string,auth:string,from:string,to:string){const body=`<?xml version="1.0"?><c:calendar-query xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav"><d:prop><d:getetag/><c:calendar-data/></d:prop><c:filter><c:comp-filter name="VCALENDAR"><c:comp-filter name="VEVENT"><c:time-range start="${from}" end="${to}"/></c:comp-filter></c:comp-filter></c:filter></c:calendar-query>`;const xml=await caldav(url,"REPORT",auth,body,"1");const doc=new DOMParser().parseFromString(xml,"application/xml");const out:any[]=[];for(const x of all(doc,"calendar-data"))out.push(...parseIcs(x.textContent||""));return out}
Deno.serve(async r=>{if(r.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(r.method!=="POST")return json({error:"Method not allowed"},405);try{const su=Deno.env.get("SUPABASE_URL"),sk=Deno.env.get("SUPABASE_PUBLISHABLE_KEY")||Deno.env.get("SUPABASE_ANON_KEY"),ah=r.headers.get("Authorization");if(!su||!sk||!ah?.startsWith("Bearer "))return json({error:"Authentication required."},401);const sb=createClient(su,sk,{global:{headers:{Authorization:ah}}});const {data:{user},error}=await sb.auth.getUser();if(error||!user)return json({error:"Authentication required."},401);const b=await r.json(),id=String(b?.appleId||"").trim(),pw=String(b?.appSpecificPassword||"").trim();if(!id||!pw)return json({error:"Apple Account email and app-specific password are required."},400);const a=basicAuth(id,pw);if(b.action==="list_calendars")return json({calendars:await listCalendars(a)});if(b.action==="fetch_events"){const u=String(b.calendarUrl||"");if(!u.includes("caldav.icloud.com"))return json({error:"Invalid Apple calendar URL."},400);if(!b.from||!b.to)return json({error:"A date range is required."},400);return json({events:await events(u,a,String(b.from),String(b.to))})}return json({error:"Unknown action."},400)}catch(e){console.error("apple-caldav-import",e);if(e instanceof AppleError)return json({error:e.message},e.status);return json({error:e instanceof Error?e.message:"Apple Calendar import failed."},500)}});
