import { supabase } from "./supabase.js";
import { formatJobPilotMoney } from "./regional-currency.js";

(() => {
  const BUSINESS_PLANS = new Set(["business", "pro"]);
  const PRO_PLANS = new Set(["pro"]);
  const esc = v => String(v ?? "").replace(/[&<>\"']/g, x => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[x]));
  const money = v => formatJobPilotMoney(Number(v) || 0);
  const status = v => String(v || "").trim().toLowerCase();
  const state = { company: null, plan: "solo", invoices: [], expenses: [], jobs: [], customers: [], members: [] };
  const hasBusiness = () => BUSINESS_PLANS.has(state.plan);
  const hasPro = () => PRO_PLANS.has(state.plan);

  function styles() {
    if (document.getElementById("jp-reports-styles")) return;
    const s = document.createElement("style"); s.id = "jp-reports-styles";
    s.textContent = `
      .jp-reports{display:flex;flex-direction:column;gap:18px}.jp-report-card{background:var(--surface,#fff);border:1px solid var(--border,#e5e7eb);border-radius:12px;padding:20px;box-shadow:var(--shadow,0 2px 8px rgba(15,23,42,.04))}
      .jp-report-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.jp-report-stat{padding:14px;border:1px solid #edf0f3;border-radius:10px}.jp-report-stat strong{display:block;font-size:22px;margin-top:4px}
      .jp-report-tabs,.jp-report-actions{display:flex;gap:8px;flex-wrap:wrap}.jp-report-tabs button.active{font-weight:700}.jp-report-filters{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.jp-report-filters label{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:700}.jp-report-filters input,.jp-report-filters select{min-width:150px}
      .jp-report-table{width:100%;border-collapse:collapse}.jp-report-table th,.jp-report-table td{text-align:left;padding:10px;border-bottom:1px solid #eef2f7;font-size:13px}.jp-report-table th{font-weight:700}.jp-report-muted{color:#64748b;font-size:13px}.jp-report-section-title{margin:0 0 5px;font-size:16px}.jp-report-section-sub{margin:0 0 14px;color:#64748b;font-size:13px}
      .jp-report-bars{display:flex;align-items:end;gap:8px;height:220px;padding-top:18px}.jp-report-bar-wrap{flex:1;min-width:22px;height:100%;display:flex;flex-direction:column;justify-content:end;align-items:center;gap:5px}.jp-report-bar{width:100%;max-width:48px;border-radius:6px 6px 0 0;background:#111827;min-height:3px}.jp-report-bar-label{font-size:10px;color:#64748b;white-space:nowrap}.jp-report-bar-value{font-size:9px;color:#64748b;white-space:nowrap}.jp-report-two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.jp-report-lock{text-align:center;padding:35px 20px}
      @media(max-width:900px){.jp-report-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.jp-report-two{grid-template-columns:1fr}}@media(max-width:600px){.jp-report-grid{grid-template-columns:1fr}.jp-report-table{display:block;overflow:auto}.jp-report-filters{align-items:stretch}.jp-report-filters label,.jp-report-filters input,.jp-report-filters select{width:100%;box-sizing:border-box}.jp-report-bars{gap:3px}}
    `; document.head.appendChild(s);
  }

  async function load() {
    const { data: { user } = {} } = await supabase.auth.getUser(); if (!user) throw new Error("Please sign in.");
    let company = window.JobPilotCompany?.company || null;
    if (!company) { const r = await supabase.from("companies").select("id,name,plan").eq("owner_id", user.id).maybeSingle(); if (r.error) throw r.error; company = r.data; }
    state.company = company; state.plan = String(company?.plan || "solo").toLowerCase(); if (!hasBusiness()) return;
    const [{data:invoices,error:ie},{data:expenses,error:ee},{data:jobs,error:je},{data:customers,error:ce}] = await Promise.all([
      supabase.from("invoices").select("id,total,status,issue_date,due_date,paid_date,customer_id").eq("company_id", company.id),
      supabase.from("expenses").select("id,description,category,amount,expense_date").eq("company_id", company.id),
      supabase.from("jobs").select("id,title,status,scheduled_date,customer_id,assigned_user_id").eq("company_id", company.id),
      supabase.from("customers").select("id,name,created_at").eq("company_id", company.id)
    ]);
    if (ie) throw ie; if (ee) throw ee; if (je) throw je; if (ce) throw ce;
    Object.assign(state, { invoices: invoices || [], expenses: expenses || [], jobs: jobs || [], customers: customers || [] });
    if (hasPro()) { try { const {data,error} = await supabase.rpc("list_my_assignable_users"); if (!error) state.members = Array.isArray(data) ? data : []; } catch { state.members = []; } }
  }

  function inRange(date,start,end) { const d=String(date||"").slice(0,10); return (!start||d>=start)&&(!end||d<=end); }
  function monthKey(d) { const x=new Date(`${String(d||"").slice(0,10)}T12:00:00`); return Number.isNaN(x.getTime())?null:`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}`; }
  function customerName(id) { return state.customers.find(x=>String(x.id)===String(id))?.name || "Unknown customer"; }
  function memberName(id) { const m=state.members.find(x=>String(x.user_id)===String(id)); return m?.full_name||m?.name||m?.email||"Unassigned"; }
  function fmtPct(n) { return `${Math.round(Number(n)||0)}%`; }

  function render() {
    const c=document.getElementById("pageContent"); if(!c)return; styles(); document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active")); document.getElementById("jobpilot-tools-button")?.classList.add("active");
    document.getElementById("pageTitle").textContent="Reports"; document.getElementById("pageSubtitle").textContent="Understand revenue, jobs, customers and costs with detailed business reports.";
    if(!hasBusiness()){c.innerHTML=`<div class="jp-reports"><div class="jp-report-card jp-report-lock"><h3>Reports</h3><p class="jp-report-muted">Advanced business reporting is available on Business and Pro.</p><button class="button primary" id="jp-reports-plans" type="button">View plans</button></div></div>`;document.getElementById("jp-reports-plans")?.addEventListener("click",()=>window.JobPilotBusinessOverview?.open?.());return;}
    c.innerHTML=`<div class="jp-reports"><div class="page-actions"><div><h2>Reports</h2><p>Detailed reports for making decisions about your business.</p></div><div class="jp-report-actions"><button class="button secondary" id="jp-reports-back" type="button">← Tools</button></div></div><div class="jp-report-tabs"><button class="button secondary active" data-report-tab="reports" type="button">Advanced Reports</button>${hasPro()?`<button class="button secondary" data-report-tab="staff" type="button">Staff Performance</button><button class="button secondary" data-report-tab="analytics" type="button">Advanced Analytics</button>`:""}</div><div id="jp-report-content"></div></div>`;
    document.getElementById("jp-reports-back")?.addEventListener("click",()=>window.JobPilotTools?.open?.()); c.querySelectorAll("[data-report-tab]").forEach(b=>b.addEventListener("click",()=>{c.querySelectorAll("[data-report-tab]").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderTab(b.dataset.reportTab);})); renderTab("reports");
  }
  function renderTab(tab){if(tab==="staff")return renderStaff();if(tab==="analytics")return renderAnalytics();renderAdvancedReports();}

  function renderAdvancedReports(){
    const c=document.getElementById("jp-report-content");if(!c)return;const now=new Date(),start=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-01`,end=now.toISOString().slice(0,10);
    c.innerHTML=`<div class="jp-report-card"><div class="jp-report-filters"><label>From<input id="jp-r-start" type="date" value="${start}"></label><label>To<input id="jp-r-end" type="date" value="${end}"></label><button class="button primary" id="jp-r-apply" type="button">Run report</button></div><p class="jp-report-muted" style="margin:12px 0 0">Revenue uses paid dates, invoices use issue dates, expenses use expense dates and jobs use scheduled dates.</p></div><div id="jp-r-output"></div>`;
    document.getElementById("jp-r-apply")?.addEventListener("click",()=>drawReports(document.getElementById("jp-r-start").value,document.getElementById("jp-r-end").value));drawReports(start,end);
  }

  function drawReports(start,end){
    const c=document.getElementById("jp-r-output");if(!c)return;
    const invIssued=state.invoices.filter(x=>inRange(x.issue_date,start,end)); const invPaid=state.invoices.filter(x=>status(x.status)==="paid"&&inRange(x.paid_date||x.issue_date,start,end)); const exp=state.expenses.filter(x=>inRange(x.expense_date,start,end)); const jobs=state.jobs.filter(x=>inRange(x.scheduled_date,start,end));
    const revenue=invPaid.reduce((a,x)=>a+Number(x.total||0),0),expenses=exp.reduce((a,x)=>a+Number(x.amount||0),0),profit=revenue-expenses;
    const outstanding=invIssued.filter(x=>!["paid","cancelled","void"].includes(status(x.status))).reduce((a,x)=>a+Number(x.total||0),0); const completed=jobs.filter(x=>["completed","complete","done"].includes(status(x.status))).length; const cancelled=jobs.filter(x=>status(x.status)==="cancelled").length;
    const completionRate=jobs.length?completed/jobs.length*100:0,avgJobRevenue=completed?revenue/completed:0,invoiceCollection=invIssued.length?invIssued.filter(x=>status(x.status)==="paid").length/invIssued.length*100:0,avgInvoice=invPaid.length?revenue/invPaid.length:0;
    const months=[];const first=new Date(`${start}T12:00:00`),last=new Date(`${end}T12:00:00`);if(!Number.isNaN(first.getTime())&&!Number.isNaN(last.getTime())){let d=new Date(first.getFullYear(),first.getMonth(),1);while(d<=last&&months.length<24){months.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`);d=new Date(d.getFullYear(),d.getMonth()+1,1);}}
    const monthlyRevenue=months.map(k=>invPaid.filter(x=>monthKey(x.paid_date||x.issue_date)===k).reduce((a,x)=>a+Number(x.total||0),0)),maxRevenue=Math.max(1,...monthlyRevenue);
    const bars=months.length?months.map((k,i)=>{const[y,m]=k.split("-");const label=new Date(Number(y),Number(m)-1,1).toLocaleDateString(undefined,{month:"short"});return `<div class="jp-report-bar-wrap"><div class="jp-report-bar-value">${money(monthlyRevenue[i])}</div><div class="jp-report-bar" style="height:${Math.max(3,Math.round(monthlyRevenue[i]/maxRevenue*170))}px" title="${money(monthlyRevenue[i])}"></div><div class="jp-report-bar-label">${label}</div></div>`;}).join(""):`<span class="jp-report-muted">Choose a valid date range.</span>`;
    const invoiceStatuses=["paid","sent","draft","overdue","cancelled","void"].map(s=>[s,invIssued.filter(x=>status(x.status)===s).length]).filter(x=>x[1]>0);const invoiceRows=invoiceStatuses.length?invoiceStatuses.map(([s,n])=>`<tr><td>${esc(s.charAt(0).toUpperCase()+s.slice(1))}</td><td>${n}</td><td>${fmtPct(invIssued.length?n/invIssued.length*100:0)}</td></tr>`).join(""):`<tr><td colspan="3">No invoices in this period.</td></tr>`;
    const jobStatuses=["completed","scheduled","in progress","pending","cancelled"].map(s=>[s,jobs.filter(x=>status(x.status)===s).length]).filter(x=>x[1]>0);const jobRows=jobStatuses.length?jobStatuses.map(([s,n])=>`<tr><td>${esc(s.replace(/\b\w/g,x=>x.toUpperCase()))}</td><td>${n}</td><td>${fmtPct(jobs.length?n/jobs.length*100:0)}</td></tr>`).join(""):`<tr><td colspan="3">No jobs in this period.</td></tr>`;
    const customerMap=new Map();invPaid.forEach(x=>{const key=String(x.customer_id||"unknown");customerMap.set(key,(customerMap.get(key)||0)+Number(x.total||0));});const topCustomers=[...customerMap.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5);const topCustomerRows=topCustomers.length?topCustomers.map(([id,total],i)=>`<tr><td>${i+1}</td><td>${esc(customerName(id))}</td><td>${money(total)}</td></tr>`).join(""):`<tr><td colspan="3">No paid customer revenue in this period.</td></tr>`;
    const expenseMap=new Map();exp.forEach(x=>{const key=String(x.category||"Uncategorised").trim()||"Uncategorised";expenseMap.set(key,(expenseMap.get(key)||0)+Number(x.amount||0));});const expenseRows=[...expenseMap.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8);const expenseTable=expenseRows.length?expenseRows.map(([cat,total])=>`<tr><td>${esc(cat)}</td><td>${money(total)}</td><td>${fmtPct(expenses?total/expenses*100:0)}</td></tr>`).join(""):`<tr><td colspan="3">No expenses in this period.</td></tr>`;
    c.innerHTML=`
      <div class="jp-report-grid"><div class="jp-report-stat"><span class="jp-report-muted">Revenue</span><strong>${money(revenue)}</strong><small class="jp-report-muted">Paid in period</small></div><div class="jp-report-stat"><span class="jp-report-muted">Expenses</span><strong>${money(expenses)}</strong><small class="jp-report-muted">Recorded in period</small></div><div class="jp-report-stat"><span class="jp-report-muted">Profit</span><strong>${money(profit)}</strong><small class="jp-report-muted">Revenue less expenses</small></div><div class="jp-report-stat"><span class="jp-report-muted">Outstanding</span><strong>${money(outstanding)}</strong><small class="jp-report-muted">Unpaid invoices issued</small></div></div>
      <div class="jp-report-grid"><div class="jp-report-stat"><span class="jp-report-muted">Completion rate</span><strong>${fmtPct(completionRate)}</strong><small class="jp-report-muted">${completed} of ${jobs.length} jobs</small></div><div class="jp-report-stat"><span class="jp-report-muted">Avg. job revenue</span><strong>${money(avgJobRevenue)}</strong><small class="jp-report-muted">Based on completed jobs</small></div><div class="jp-report-stat"><span class="jp-report-muted">Invoice collection</span><strong>${fmtPct(invoiceCollection)}</strong><small class="jp-report-muted">Paid invoice count</small></div><div class="jp-report-stat"><span class="jp-report-muted">Avg. invoice</span><strong>${money(avgInvoice)}</strong><small class="jp-report-muted">Paid invoices</small></div></div>
      <div class="jp-report-card"><h3 class="jp-report-section-title">Revenue trend</h3><p class="jp-report-section-sub">Paid revenue by month for the selected period.</p><div class="jp-report-bars">${bars}</div></div>
      <div class="jp-report-two"><div class="jp-report-card"><h3 class="jp-report-section-title">Invoice breakdown</h3><p class="jp-report-section-sub">Status of invoices issued during the period.</p><table class="jp-report-table"><thead><tr><th>Status</th><th>Count</th><th>Share</th></tr></thead><tbody>${invoiceRows}</tbody></table></div><div class="jp-report-card"><h3 class="jp-report-section-title">Job breakdown</h3><p class="jp-report-section-sub">Job statuses for scheduled jobs in the period.</p><table class="jp-report-table"><thead><tr><th>Status</th><th>Count</th><th>Share</th></tr></thead><tbody>${jobRows}</tbody></table></div></div>
      <div class="jp-report-two"><div class="jp-report-card"><h3 class="jp-report-section-title">Top customers</h3><p class="jp-report-section-sub">Customers generating the most paid revenue.</p><table class="jp-report-table"><thead><tr><th>#</th><th>Customer</th><th>Revenue</th></tr></thead><tbody>${topCustomerRows}</tbody></table></div><div class="jp-report-card"><h3 class="jp-report-section-title">Expenses by category</h3><p class="jp-report-section-sub">Where your recorded costs are going.</p><table class="jp-report-table"><thead><tr><th>Category</th><th>Amount</th><th>Share</th></tr></thead><tbody>${expenseTable}</tbody></table></div></div>
      <div class="jp-report-card"><h3 class="jp-report-section-title">Period activity</h3><table class="jp-report-table"><tbody><tr><td>Jobs scheduled</td><td><strong>${jobs.length}</strong></td></tr><tr><td>Jobs completed</td><td><strong>${completed}</strong></td></tr><tr><td>Jobs cancelled</td><td><strong>${cancelled}</strong></td></tr><tr><td>Invoices issued</td><td><strong>${invIssued.length}</strong></td></tr><tr><td>Paid invoices</td><td><strong>${invPaid.length}</strong></td></tr><tr><td>Expenses recorded</td><td><strong>${exp.length}</strong></td></tr></tbody></table></div>`;
  }

  function renderStaff(){const c=document.getElementById("jp-report-content");if(!c)return;const active=state.jobs.filter(x=>status(x.status)!=="cancelled"),revenueBy=new Map();state.invoices.filter(x=>status(x.status)==="paid").forEach(i=>{const j=state.jobs.find(x=>String(x.customer_id)===String(i.customer_id));if(j?.assigned_user_id)revenueBy.set(String(j.assigned_user_id),(revenueBy.get(String(j.assigned_user_id))||0)+Number(i.total||0));});const rows=state.members.map(m=>{const jobs=active.filter(j=>String(j.assigned_user_id)===String(m.user_id)),completed=jobs.filter(j=>["completed","complete","done"].includes(status(j.status))).length;return{name:memberName(m.user_id),jobs:jobs.length,completed,revenue:revenueBy.get(String(m.user_id))||0,rate:jobs.length?completed/jobs.length*100:0};}).sort((a,b)=>b.revenue-a.revenue);c.innerHTML=`<div class="jp-report-card"><h3 class="jp-report-section-title">Staff Performance</h3><p class="jp-report-section-sub">Performance based on assigned jobs and paid invoice data currently available in JobPilot.</p><table class="jp-report-table"><thead><tr><th>Staff member</th><th>Jobs</th><th>Completed</th><th>Completion</th><th>Revenue</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td><strong>${esc(r.name)}</strong></td><td>${r.jobs}</td><td>${r.completed}</td><td>${fmtPct(r.rate)}</td><td>${money(r.revenue)}</td></tr>`).join(""):"<tr><td colspan=\"5\">No staff data available.</td></tr>"}</tbody></table></div>`;}

  function renderAnalytics(){const c=document.getElementById("jp-report-content");if(!c)return;const months=[],now=new Date();for(let i=11;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);months.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`);}const rev=months.map(k=>state.invoices.filter(x=>status(x.status)==="paid"&&monthKey(x.paid_date||x.issue_date)===k).reduce((a,x)=>a+Number(x.total||0),0)),exp=months.map(k=>state.expenses.filter(x=>monthKey(x.expense_date)===k).reduce((a,x)=>a+Number(x.amount||0),0)),max=Math.max(1,...rev,...exp),labels=months.map(k=>{const[y,m]=k.split("-");return new Date(Number(y),Number(m)-1,1).toLocaleDateString(undefined,{month:"short"});}),bars=months.map((_,i)=>`<div class="jp-report-bar-wrap"><div class="jp-report-bar-value">${money(rev[i])}</div><div class="jp-report-bar" title="Revenue ${money(rev[i])}" style="height:${Math.max(3,Math.round(rev[i]/max*170))}px"></div><span class="jp-report-bar-label">${labels[i]}</span></div>`).join(""),customers=state.customers.length,newCustomers=state.customers.filter(x=>monthKey(x.created_at)>=months[0]).length,totalRev=rev.reduce((a,b)=>a+b,0),totalExp=exp.reduce((a,b)=>a+b,0);c.innerHTML=`<div class="jp-report-grid"><div class="jp-report-stat"><span class="jp-report-muted">12-month revenue</span><strong>${money(totalRev)}</strong></div><div class="jp-report-stat"><span class="jp-report-muted">12-month expenses</span><strong>${money(totalExp)}</strong></div><div class="jp-report-stat"><span class="jp-report-muted">12-month profit</span><strong>${money(totalRev-totalExp)}</strong></div><div class="jp-report-stat"><span class="jp-report-muted">Customers</span><strong>${customers}</strong><small class="jp-report-muted">${newCustomers} added in period</small></div></div><div class="jp-report-card"><h3 class="jp-report-section-title">Revenue trend — last 12 months</h3><p class="jp-report-section-sub">Monthly paid revenue.</p><div class="jp-report-bars">${bars}</div></div><div class="jp-report-card"><h3 class="jp-report-section-title">Business metrics</h3><table class="jp-report-table"><tbody><tr><td>Average monthly revenue</td><td><strong>${money(totalRev/12)}</strong></td></tr><tr><td>Average monthly expenses</td><td><strong>${money(totalExp/12)}</strong></td></tr><tr><td>Profit margin</td><td><strong>${fmtPct(totalRev?(totalRev-totalExp)/totalRev*100:0)}</strong></td></tr><tr><td>Active jobs</td><td>${state.jobs.filter(x=>status(x.status)!=="cancelled").length}</td></tr></tbody></table></div>`;}

  window.JobPilotBusinessReports={open:()=>{const c=document.getElementById("pageContent");if(c)c.innerHTML=`<div class="jp-reports"><div class="jp-report-card"><p class="jp-report-muted">Loading Reports…</p></div></div>`;load().then(render).catch(e=>{if(c)c.innerHTML=`<div class="jp-report-card"><strong>Could not load Reports.</strong><p class="jp-report-muted">${esc(e.message||e)}</p></div>`;});}};
})();
