import { supabase } from "./supabase.js";
import { formatJobPilotMoney } from "./regional-currency.js";

(() => {
  const BUSINESS_PLANS=new Set(["business","pro"]), PRO_PLANS=new Set(["pro"]);
  const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
  const money=v=>formatJobPilotMoney(Number(v)||0);
  const state={company:null,plan:"solo",invoices:[],expenses:[],jobs:[],customers:[],members:[]};
  const hasBusiness=()=>BUSINESS_PLANS.has(state.plan), hasPro=()=>PRO_PLANS.has(state.plan);
  function styles(){if(document.getElementById("jp-reports-styles"))return;const s=document.createElement("style");s.id="jp-reports-styles";s.textContent=`
    .jp-reports{display:flex;flex-direction:column;gap:18px}.jp-report-card{background:var(--surface,#fff);border:1px solid var(--border,#e5e7eb);border-radius:12px;padding:20px;box-shadow:var(--shadow,0 2px 8px rgba(15,23,42,.04))}.jp-report-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.jp-report-stat{padding:14px;border:1px solid #edf0f3;border-radius:10px}.jp-report-stat strong{display:block;font-size:22px;margin-top:4px}.jp-report-tabs{display:flex;gap:8px;flex-wrap:wrap}.jp-report-tabs button.active{font-weight:700}.jp-report-filters{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.jp-report-filters label{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:700}.jp-report-filters input,.jp-report-filters select{min-width:150px}.jp-report-table{width:100%;border-collapse:collapse}.jp-report-table th,.jp-report-table td{text-align:left;padding:10px;border-bottom:1px solid #eef2f7;font-size:13px}.jp-report-table th{font-weight:700}.jp-report-muted{color:#64748b;font-size:13px}.jp-report-bars{display:flex;align-items:end;gap:8px;height:210px;padding-top:18px}.jp-report-bar-wrap{flex:1;min-width:22px;height:100%;display:flex;flex-direction:column;justify-content:end;align-items:center;gap:5px}.jp-report-bar{width:100%;max-width:48px;border-radius:6px 6px 0 0;background:#111827;min-height:3px}.jp-report-bar-label{font-size:10px;color:#64748b;white-space:nowrap}.jp-report-lock{text-align:center;padding:35px 20px}.jp-report-lock h3{margin:0 0 8px}.jp-report-actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:900px){.jp-report-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.jp-report-grid{grid-template-columns:1fr}.jp-report-table{display:block;overflow:auto}.jp-report-filters{align-items:stretch}.jp-report-filters label,.jp-report-filters input{width:100%;box-sizing:border-box}}
  `;document.head.appendChild(s)}
  async function load(){const {data:{user}={}}=await supabase.auth.getUser();if(!user)throw new Error("Please sign in.");let company=window.JobPilotCompany?.company||null;if(!company){const r=await supabase.from("companies").select("id,name,plan").eq("owner_id",user.id).maybeSingle();if(r.error)throw r.error;company=r.data}state.company=company;state.plan=String(company?.plan||"solo").toLowerCase();if(!hasBusiness())return;
    const [{data:invoices,error:ie},{data:expenses,error:ee},{data:jobs,error:je},{data:customers,error:ce}]=await Promise.all([
      supabase.from("invoices").select("id,total,status,issue_date,due_date,paid_date,customer_id").eq("company_id",company.id),
      supabase.from("expenses").select("id,amount,expense_date").eq("company_id",company.id),
      supabase.from("jobs").select("id,title,status,scheduled_date,customer_id,assigned_user_id").eq("company_id",company.id),
      supabase.from("customers").select("id,name,created_at").eq("company_id",company.id)
    ]);if(ie)throw ie;if(ee)throw ee;if(je)throw je;if(ce)throw ce;Object.assign(state,{invoices:invoices||[],expenses:expenses||[],jobs:jobs||[],customers:customers||[]});
    if(hasPro()){try{const {data,error}=await supabase.rpc("list_my_assignable_users");if(!error)state.members=Array.isArray(data)?data:[]}catch{state.members=[]}}
  }
  function inRange(date,start,end){return (!start||String(date||"")>=start)&&(!end||String(date||"")<=end)}
  function monthKey(d){const x=new Date(`${d}T12:00:00`);return Number.isNaN(x.getTime())?null:`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}`}
  function memberName(id){const m=state.members.find(x=>String(x.user_id)===String(id));return m?.full_name||m?.name||m?.email||"Unassigned"}
  function render(){const c=document.getElementById("pageContent");if(!c)return;styles();document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));document.getElementById("jobpilot-tools-button")?.classList.add("active");document.getElementById("pageTitle").textContent="Reports";document.getElementById("pageSubtitle").textContent="Business reports, staff performance and advanced analytics.";if(!hasBusiness()){c.innerHTML=`<div class="jp-reports"><div class="jp-report-card jp-report-lock"><h3>Reports</h3><p class="jp-report-muted">Advanced business reporting is available on Business and Pro.</p><button class="button primary" id="jp-reports-plans" type="button">View plans</button></div></div>`;document.getElementById("jp-reports-plans")?.addEventListener("click",()=>window.JobPilotBusinessOverview?.open?.());return}c.innerHTML=`<div class="jp-reports"><div class="page-actions"><div><h2>Reports</h2><p>Turn your JobPilot data into useful business reports.</p></div><div class="jp-report-actions"><button class="button secondary" id="jp-reports-back" type="button">← Tools</button></div></div><div class="jp-report-tabs"><button class="button secondary active" data-report-tab="reports" type="button">Advanced Reports</button>${hasPro()?`<button class="button secondary" data-report-tab="staff" type="button">Staff Performance</button><button class="button secondary" data-report-tab="analytics" type="button">Advanced Analytics</button>`:""}</div><div id="jp-report-content"></div></div>`;document.getElementById("jp-reports-back")?.addEventListener("click",()=>window.JobPilotTools?.open?.());c.querySelectorAll("[data-report-tab]").forEach(b=>b.addEventListener("click",()=>{c.querySelectorAll("[data-report-tab]").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderTab(b.dataset.reportTab)}));renderTab("reports")}
  function renderTab(tab){if(tab==="staff")return renderStaff();if(tab==="analytics")return renderAnalytics();renderAdvancedReports()}
  function renderAdvancedReports(){const c=document.getElementById("jp-report-content");if(!c)return;const now=new Date(),start=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-01`,end=now.toISOString().slice(0,10);c.innerHTML=`<div class="jp-report-card"><div class="jp-report-filters"><label>From<input id="jp-r-start" type="date" value="${start}"></label><label>To<input id="jp-r-end" type="date" value="${end}"></label><button class="button primary" id="jp-r-apply" type="button">Run report</button></div></div><div id="jp-r-output"></div>`;document.getElementById("jp-r-apply")?.addEventListener("click",()=>drawReports(document.getElementById("jp-r-start").value,document.getElementById("jp-r-end").value));drawReports(start,end)}
  function drawReports(start,end){const c=document.getElementById("jp-r-output");if(!c)return;const inv=state.invoices.filter(x=>inRange(x.issue_date||x.paid_date,start,end));const exp=state.expenses.filter(x=>inRange(x.expense_date,start,end));const jobs=state.jobs.filter(x=>inRange(x.scheduled_date,start,end));const paid=inv.filter(x=>!['cancelled','void'].includes(String(x.status||"").toLowerCase())&&String(x.status||"").toLowerCase()==="paid").reduce((a,x)=>a+Number(x.total||0),0);const outstanding=inv.filter(x=>!['cancelled','void','paid'].includes(String(x.status||"").toLowerCase())).reduce((a,x)=>a+Number(x.total||0),0);const expenses=exp.reduce((a,x)=>a+Number(x.amount||0),0);const completed=jobs.filter(x=>String(x.status||"").toLowerCase()==="completed").length;const avg=completed?paid/completed:0;c.innerHTML=`<div class="jp-report-grid"><div class="jp-report-stat"><span class="jp-report-muted">Revenue</span><strong>${money(paid)}</strong></div><div class="jp-report-stat"><span class="jp-report-muted">Expenses</span><strong>${money(expenses)}</strong></div><div class="jp-report-stat"><span class="jp-report-muted">Outstanding</span><strong>${money(outstanding)}</strong></div><div class="jp-report-stat"><span class="jp-report-muted">Completed jobs</span><strong>${completed}</strong></div></div><div class="jp-report-card"><h3>Report summary</h3><table class="jp-report-table"><tbody><tr><td>Profit</td><td><strong>${money(paid-expenses)}</strong></td></tr><tr><td>Average revenue per completed job</td><td><strong>${money(avg)}</strong></td></tr><tr><td>Total jobs in period</td><td>${jobs.length}</td></tr><tr><td>Invoices issued</td><td>${inv.length}</td></tr><tr><td>Expenses recorded</td><td>${exp.length}</td></tr></tbody></table></div>`}
  function renderStaff(){const c=document.getElementById("jp-report-content");if(!c)return;const active=state.jobs.filter(x=>String(x.status||"").toLowerCase()!=="cancelled");const revenueBy=new Map();state.invoices.filter(x=>String(x.status||"").toLowerCase()==="paid").forEach(i=>{const j=state.jobs.find(x=>String(x.customer_id)===String(i.customer_id));if(j?.assigned_user_id)revenueBy.set(String(j.assigned_user_id),(revenueBy.get(String(j.assigned_user_id))||0)+Number(i.total||0))});const rows=state.members.map(m=>{const jobs=active.filter(j=>String(j.assigned_user_id)===String(m.user_id));const completed=jobs.filter(j=>String(j.status||"").toLowerCase()==="completed").length;return {name:memberName(m.user_id),jobs:jobs.length,completed,revenue:revenueBy.get(String(m.user_id))||0,rate:jobs.length?Math.round(completed/jobs.length*100):0}}).sort((a,b)=>b.revenue-a.revenue);c.innerHTML=`<div class="jp-report-card"><h3>Staff Performance</h3><p class="jp-report-muted">Performance based on assigned jobs and paid invoice data currently available in JobPilot.</p><table class="jp-report-table"><thead><tr><th>Staff member</th><th>Jobs</th><th>Completed</th><th>Completion</th><th>Revenue</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td><strong>${esc(r.name)}</strong></td><td>${r.jobs}</td><td>${r.completed}</td><td>${r.rate}%</td><td>${money(r.revenue)}</td></tr>`).join(""):"<tr><td colspan=\"5\">No staff data available.</td></tr>"}</tbody></table></div>`}
  function renderAnalytics(){const c=document.getElementById("jp-report-content");if(!c)return;const months=[];const now=new Date();for(let i=11;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1);months.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`)}const rev=months.map(k=>state.invoices.filter(x=>monthKey(x.paid_date||x.issue_date)===k&&String(x.status||"").toLowerCase()==="paid").reduce((a,x)=>a+Number(x.total||0),0));const exp=months.map(k=>state.expenses.filter(x=>monthKey(x.expense_date)===k).reduce((a,x)=>a+Number(x.amount||0),0));const max=Math.max(1,...rev,...exp);const labels=months.map(k=>{const [y,m]=k.split("-");return new Date(Number(y),Number(m)-1,1).toLocaleDateString(undefined,{month:"short"})});const bars=months.map((_,i)=>`<div class="jp-report-bar-wrap"><div class="jp-report-bar" title="Revenue ${money(rev[i])}" style="height:${Math.max(3,Math.round(rev[i]/max*170))}px"></div><span class="jp-report-bar-label">${labels[i]}</span></div>`).join("");const customers=state.customers.length,newCustomers=state.customers.filter(x=>monthKey(x.created_at)>=months[0]).length;const totalRev=rev.reduce((a,b)=>a+b,0),totalExp=exp.reduce((a,b)=>a+b,0);c.innerHTML=`<div class="jp-report-grid"><div class="jp-report-stat"><span class="jp-report-muted">12-month revenue</span><strong>${money(totalRev)}</strong></div><div class="jp-report-stat"><span class="jp-report-muted">12-month expenses</span><strong>${money(totalExp)}</strong></div><div class="jp-report-stat"><span class="jp-report-muted">12-month profit</span><strong>${money(totalRev-totalExp)}</strong></div><div class="jp-report-stat"><span class="jp-report-muted">Customers</span><strong>${customers}</strong><small class="jp-report-muted">${newCustomers} added in period</small></div></div><div class="jp-report-card"><h3>Revenue trend — last 12 months</h3><p class="jp-report-muted">Monthly paid revenue.</p><div class="jp-report-bars">${bars}</div></div><div class="jp-report-card"><h3>Business metrics</h3><table class="jp-report-table"><tbody><tr><td>Average monthly revenue</td><td><strong>${money(totalRev/12)}</strong></td></tr><tr><td>Average monthly expenses</td><td><strong>${money(totalExp/12)}</strong></td></tr><tr><td>Profit margin</td><td><strong>${totalRev?Math.round((totalRev-totalExp)/totalRev*100):0}%</strong></td></tr><tr><td>Active jobs</td><td>${state.jobs.filter(x=>String(x.status||"").toLowerCase()!=="cancelled").length}</td></tr></tbody></table></div>`}
  window.JobPilotBusinessReports={open:()=>{const c=document.getElementById("pageContent");if(c){c.innerHTML=`<div class="jp-reports"><div class="jp-report-card"><p class="jp-report-muted">Loading Reports…</p></div></div>`}load().then(render).catch(e=>{if(c)c.innerHTML=`<div class="jp-report-card"><strong>Could not load Reports.</strong><p class="jp-report-muted">${esc(e.message||e)}</p></div>`})}};
})();
