import { supabase } from "./supabase.js";

const esc = value => String(value ?? "").replace(/[&<>\"']/g, char => ({
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  "\"": "&quot;",
  "'": "&#039;"
}[char]));

function modal(body) {
  const existing = document.getElementById("jobpilot-email-quote-modal");
  if (existing) existing.remove();
  const modal = document.createElement("div");
  modal.id = "jobpilot-email-quote-modal";
  modal.className = "modal show";
  modal.innerHTML = `<div class="modal-content" style="max-width:720px;width:94vw">${body}</div>`;
  document.body.appendChild(modal);
  modal.querySelectorAll(".close").forEach(button => {
    button.addEventListener("click", () => modal.remove());
  });
  return modal;
}

async function getQuoteFromCurrentPage() {
  const title = document.getElementById("pageTitle")?.textContent || "";
  const quoteNumber = title.replace(/^Quote #/i, "").trim();
  if (!quoteNumber) throw new Error("The quote could not be identified.");

  const { data: quote, error } = await supabase
    .from("quotes")
    .select("*")
    .eq("quote_number", quoteNumber)
    .maybeSingle();
  if (error) throw error;
  if (!quote) throw new Error("Quote could not be found.");

  const { data: customer, error: customerError } = await supabase
    .from("customers")
    .select("id, name, email")
    .eq("id", quote.customer_id)
    .maybeSingle();
  if (customerError) throw customerError;
  if (!customer) throw new Error("The customer attached to this quote could not be found.");

  return { quote, customer };
}

async function openEmailQuote() {
  const { quote, customer } = await getQuoteFromCurrentPage();

  if (String(quote.status).toLowerCase() === "converted") {
    alert("This quote has already been converted to a job.");
    return;
  }

  const settings = (() => {
    try { return JSON.parse(localStorage.getItem("jobpilot_settings") || "{}"); }
    catch { return {}; }
  })();
  const businessName = settings.businessName || "our business";
  const total = `£${Number(quote.total || 0).toFixed(2)}`;
  const defaultMessage =
    `Hi ${customer.name},\n\n` +
    `Please find attached your quotation from ${businessName}.\n\n` +
    `Quote #${quote.quote_number || "—"}\n` +
    `Description: ${quote.title || quote.description || "Quotation"}\n` +
    `Total: ${total}\n` +
    (quote.valid_until ? `Valid until: ${quote.valid_until}\n\n` : "\n") +
    `Please let us know if you have any questions or would like to go ahead.\n\n` +
    `Kind regards,\n${businessName}`;

  const m = modal(`
    <div class="modal-header">
      <div>
        <h2>Email Quote</h2>
        <p>Prepare the quote email and attach the PDF generated by JobPilot.</p>
      </div>
      <button class="close" type="button">×</button>
    </div>
    <form id="jobpilotEmailQuoteForm">
      <label>To</label>
      <input id="jobpilotEmailTo" type="email" required value="${esc(customer.email || "")}" placeholder="customer@example.com">

      <label>Subject</label>
      <input id="jobpilotEmailSubject" required value="${esc(`Quotation ${quote.quote_number || ""} from ${businessName}`)}">

      <label>Message</label>
      <textarea id="jobpilotEmailMessage" rows="12" required>${esc(defaultMessage)}</textarea>

      <p class="muted" style="margin-top:10px">
        JobPilot will generate the latest PDF first, then open your email app with the message ready. Attach the downloaded PDF before sending.
      </p>

      <div id="jobpilotEmailQuoteMessage" class="muted" style="margin-top:10px"></div>

      <div class="modal-actions">
        <button type="button" class="button secondary close">Cancel</button>
        <button type="submit" class="button primary">📧 Generate PDF & Open Email</button>
      </div>
    </form>
  `);

  m.querySelector("#jobpilotEmailQuoteForm").addEventListener("submit", async event => {
    event.preventDefault();
    const button = m.querySelector("button[type=submit]");
    const message = m.querySelector("#jobpilotEmailQuoteMessage");
    const to = m.querySelector("#jobpilotEmailTo").value.trim();
    const subject = m.querySelector("#jobpilotEmailSubject").value.trim();
    const body = m.querySelector("#jobpilotEmailMessage").value.trim();

    if (!to) {
      message.textContent = "Enter the customer's email address.";
      return;
    }

    button.disabled = true;
    button.textContent = "Preparing PDF…";
    message.textContent = "Generating the latest quote PDF…";

    try {
      if (typeof window.__jobpilotGenerateQuotePdf !== "function") {
        throw new Error("The quote PDF system is not available. Please refresh JobPilot and try again.");
      }

      await window.__jobpilotGenerateQuotePdf(quote.id);

      await supabase
        .from("quotes")
        .update({ status: "sent" })
        .eq("id", quote.id)
        .neq("status", "converted");

      const mailto = `mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
      window.location.href = mailto;
      m.remove();
    } catch (error) {
      console.error("JobPilot email quote:", error);
      message.textContent = error.message || "The quote email could not be prepared.";
      button.disabled = false;
      button.textContent = "📧 Generate PDF & Open Email";
    }
  });
}

function installEmailButtons() {
  const deleteButton = document.getElementById("deleteQuote");
  if (!deleteButton) return;
  if (deleteButton.parentElement?.querySelector("#jobpilotEmailQuoteButton")) return;

  const button = document.createElement("button");
  button.id = "jobpilotEmailQuoteButton";
  button.type = "button";
  button.className = "button primary";
  button.textContent = "📧 Email Quote";
  button.addEventListener("click", async event => {
    event.stopPropagation();
    button.disabled = true;
    try {
      await openEmailQuote();
    } catch (error) {
      console.error("JobPilot email quote:", error);
      alert(error.message || "The quote email could not be prepared.");
    } finally {
      button.disabled = false;
    }
  });

  deleteButton.parentElement.insertBefore(button, deleteButton);
}

const observer = new MutationObserver(installEmailButtons);
observer.observe(document.body, { childList: true, subtree: true });
installEmailButtons();
