import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ANON_KEY=Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SUPABASE_PUBLISHABLE_KEY")||"";
const CLIENT_ID=Deno.env.get("QUICKBOOKS_CLIENT_ID");
const CLIENT_SECRET=Deno.env.get("QUICKBOOKS_CLIENT_SECRET");
const API_BASE="https://quickbooks.api.intuit.com";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,"Content-Type":"application/json"}});
const db=(path:string,init:RequestInit={})=>fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,"Content-Type":"application/json",...(init.headers||{})}});
async function userFromRequest(req:Request){const auth=req.headers.get("Authorization");if(!auth?.startsWith("Bearer "))return null;const c=createClient(SUPABASE_URL,ANON_KEY,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await c.auth.getUser();return error||!data.user?null:data.user;}
async function getConnection(userId:string){const r=await db(`quickbooks_connections?user_id=eq.${encodeURIComponent(userId)}&select=*`);const rows=await r.json().catch(()=>[]);if(!r.ok||!rows?.[0])throw new Error("QuickBooks is not connected.");let c=rows[0];if(Date.parse(c.access_token_expires_at||"")>Date.now()+120000)return c;if(!CLIENT_ID||!CLIENT_SECRET||!c.refresh_token)throw new Error("QuickBooks connection needs to be reauthorised.");const r2=await fetch("https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",{method:"POST",headers:{Authorization:`Basic ${btoa(`${CLIENT_ID}:${CLIENT_SECRET}`)}`,"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:c.refresh_token})});const t=await r2.json().catch(()=>({}));if(!r2.ok)throw new Error(t.error_description||t.error||"QuickBooks token refresh failed.");const update={access_token:t.access_token,refresh_token:t.refresh_token||c.refresh_token,access_token_expires_at:new Date(Date.now()+Number(t.expires_in||3600)*1000).toISOString(),refresh_token_expires_at:t.x_refresh_token_expires_in?new Date(Date.now()+Number(t.x_refresh_token_expires_in)*1000).toISOString():c.refresh_token_expires_at,updated_at:new Date().toISOString()};const saved=await db(`quickbooks_connections?user_id=eq.${encodeURIComponent(userId)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify(update)});if(!saved.ok)throw new Error("Could not save refreshed QuickBooks tokens.");return {...c,...update};}
async function qb(c:any,path:string,init:RequestInit={}){const r=await fetch(`${API_BASE}/v3/company/${encodeURIComponent(c.realm_id)}${path}${path.includes("?")?"&":"?"}minorversion=75`,{...init,headers:{Authorization:`Bearer ${c.access_token}`,Accept:"application/json","Content-Type":"application/json",...(init.headers||{})}});const body=await r.json().catch(()=>({}));if(!r.ok){const detail=body?.Fault?.Error?.map((e:any)=>e.Detail||e.Message).filter(Boolean).join("; ");throw new Error(detail||`QuickBooks API error ${r.status}`);}return body;}
async function getCompanyId(userId:string){const m=await db(`company_members?user_id=eq.${encodeURIComponent(userId)}&status=eq.active&select=company_id&limit=1`);const members=await m.json().catch(()=>[]);if(members?.[0]?.company_id)return members[0].company_id;const o=await db(`companies?owner_id=eq.${encodeURIComponent(userId)}&select=id&limit=1`);const companies=await o.json().catch(()=>[]);return companies?.[0]?.id||null;}
const esc=(v:any)=>String(v??"").replace(/'/g,"''");
const cleanName=(v:any)=>String(v||"Customer").trim().replace(/\s+/g," ").slice(0,500);
async function findCustomer(c:any,customer:any){const email=String(customer.email||"").trim();const name=cleanName(customer.name);const q=email?`select * from Customer where PrimaryEmailAddr = '${esc(email)}' maxresults 1`:`select * from Customer where DisplayName = '${esc(name)}' maxresults 1`;const result=await qb(c,`/query?query=${encodeURIComponent(q)}`);return result?.QueryResponse?.Customer?.[0]||null;}
function customerPayload(customer:any,existing:any=null){return {...(existing?.Id?{Id:existing.Id,SyncToken:existing.SyncToken}:{}),DisplayName:cleanName(customer.name),GivenName:cleanName(customer.name).split(" ")[0].slice(0,100),...(customer.email?{PrimaryEmailAddr:{Address:String(customer.email).trim()}}:{}),...(customer.phone?{PrimaryPhone:{FreeFormNumber:String(customer.phone).slice(0,30)}}:{}),...(customer.address_line1||customer.city||customer.postcode?{BillAddr:{Line1:customer.address_line1||undefined,Line2:customer.address_line2||undefined,City:customer.city||undefined,CountrySubDivisionCode:customer.address_region||undefined,PostalCode:customer.postcode||undefined}}:{})};}
async function syncCustomer(c:any,customer:any){let remote=null;if(customer.quickbooks_customer_id){try{remote=(await qb(c,`/customer/${encodeURIComponent(customer.quickbooks_customer_id)}`))?.Customer||null;}catch{}}if(!remote)remote=await findCustomer(c,customer);const result=await qb(c,"/customer",{method:"POST",body:JSON.stringify(customerPayload(customer,remote))});const saved=result?.Customer;if(!saved?.Id)throw new Error(`QuickBooks did not return a customer ID for ${customer.name}.`);await db(`customers?id=eq.${encodeURIComponent(customer.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({quickbooks_customer_id:saved.Id})});return saved;}
async function loadItems(invoiceId:string){const r=await db(`invoice_items?invoice_id=eq.${encodeURIComponent(invoiceId)}&select=*`);const items=await r.json().catch(()=>[]);return r.ok&&Array.isArray(items)?items:[];}
async function syncInvoice(c:any,invoice:any,customer:any,items:any[]){const remoteCustomer=await syncCustomer(c,customer);let remote=null;if(invoice.quickbooks_invoice_id){try{remote=(await qb(c,`/invoice/${encodeURIComponent(invoice.quickbooks_invoice_id)}`))?.Invoice||null;}catch{}}if(!remote){const q=`select * from Invoice where DocNumber = '${esc(invoice.invoice_number||"")}' maxresults 1`;remote=(await qb(c,`/query?query=${encodeURIComponent(q)}`))?.QueryResponse?.Invoice?.[0]||null;}const source=items.length?items:[{description:invoice.description||invoice.invoice_number||"JobPilot invoice",quantity:1,unit_price:Number(invoice.total||0),total:Number(invoice.total||0)}];const lines=source.map((item:any)=>({DetailType:"SalesItemLineDetail",Amount:Number(item.total??Number(item.quantity||1)*Number(item.unit_price||0)),Description:String(item.description||"Service").slice(0,4000),SalesItemLineDetail:{Qty:Number(item.quantity||1),UnitPrice:Number(item.unit_price||0)}}));const payload:any={...(remote?.Id?{Id:remote.Id,SyncToken:remote.SyncToken}:{}),CustomerRef:{value:String(remoteCustomer.Id)},...(invoice.invoice_number?{DocNumber:String(invoice.invoice_number).slice(0,21)}:{}),...(invoice.issue_date?{TxnDate:invoice.issue_date}:{}),...(invoice.due_date?{DueDate:invoice.due_date}:{}),Line:lines,GlobalTaxCalculation:"NotApplicable"};const result=await qb(c,"/invoice",{method:"POST",body:JSON.stringify(payload)});const saved=result?.Invoice;if(!saved?.Id)throw new Error(`QuickBooks did not return an invoice ID for ${invoice.invoice_number}.`);await db(`invoices?id=eq.${encodeURIComponent(invoice.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({quickbooks_invoice_id:saved.Id,quickbooks_sync_status:"synced",quickbooks_sync_error:null,quickbooks_synced_at:new Date().toISOString()})});return saved;}
async function pullPaymentStatus(c:any,userId:string,cid:string|null){const filter=cid?`company_id=eq.${encodeURIComponent(cid)}`:`user_id=eq.${encodeURIComponent(userId)}`;const r=await db(`invoices?${filter}&quickbooks_invoice_id=not.is.null&select=id,quickbooks_invoice_id,status,paid_date`);const invoices=await r.json().catch(()=>[]);if(!r.ok)throw new Error("Could not load synced JobPilot invoices.");let updated=0;for(const inv of invoices){try{const remote=(await qb(c,`/invoice/${encodeURIComponent(inv.quickbooks_invoice_id)}`))?.Invoice;if(!remote)continue;const paid=Number(remote.Balance||0)<=0.005;if(paid&&inv.status!=="paid"){await db(`invoices?id=eq.${encodeURIComponent(inv.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"paid",paid_date:new Date().toISOString().slice(0,10)})});updated++;}}catch(e){console.error("QuickBooks payment sync",inv.id,e);}}return updated;}
async function syncAll(c:any,userId:string){const cid=await getCompanyId(userId);const filter=cid?`company_id=eq.${encodeURIComponent(cid)}`:`user_id=eq.${encodeURIComponent(userId)}`;const cr=await db(`customers?${filter}&select=*`);const customers=await cr.json().catch(()=>[]);if(!cr.ok)throw new Error("Could not load JobPilot customers.");let customersSynced=0,customerErrors=0;for(const customer of customers){try{await syncCustomer(c,customer);customersSynced++;}catch(e){customerErrors++;console.error("QuickBooks customer sync",customer.id,e);}}const ir=await db(`invoices?${filter}&select=*`);const invoices=await ir.json().catch(()=>[]);if(!ir.ok)throw new Error("Could not load JobPilot invoices.");const map=new Map(customers.map((x:any)=>[x.id,x]));let invoicesSynced=0,invoiceErrors=0;for(const invoice of invoices){const customer=map.get(invoice.customer_id);if(!customer){invoiceErrors++;continue;}try{await syncInvoice(c,invoice,customer,await loadItems(invoice.id));invoicesSynced++;}catch(e){invoiceErrors++;await db(`invoices?id=eq.${encodeURIComponent(invoice.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({quickbooks_sync_status:"error",quickbooks_sync_error:e instanceof Error?e.message:String(e),quickbooks_synced_at:new Date().toISOString()})});}}const paymentsUpdated=await pullPaymentStatus(c,userId,cid);return{customersSynced,customerErrors,invoicesSynced,invoiceErrors,paymentsUpdated};}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});try{const user=await userFromRequest(req);if(!user)return json({error:"Missing or invalid authorization."},401);const c=await getConnection(user.id);const body=await req.json().catch(()=>({}));const action=String(body.action||"sync").toLowerCase();if(action==="payments"){const updated=await pullPaymentStatus(c,user.id,await getCompanyId(user.id));return json({ok:true,paymentsUpdated:updated});}return json({ok:true,...await syncAll(c,user.id)});}catch(e){console.error("QuickBooks sync error",e);return json({error:e instanceof Error?e.message:"Unexpected QuickBooks sync error."},500);}});