import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY") || Deno.env.get("SUPABASE_PUBLISHABLE_KEY") || "";
const XERO_CLIENT_ID = Deno.env.get("XERO_CLIENT_ID");
const XERO_CLIENT_SECRET = Deno.env.get("XERO_CLIENT_SECRET");
const XERO_API = "https://api.xero.com/api.xro/2.0";
const CORS = { "Access-Control-Allow-Origin":"*", "Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods":"POST, OPTIONS" };
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,"Content-Type":"application/json"}});
const db=async(path:string,init:RequestInit={})=>fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,"Content-Type":"application/json",...(init.headers||{})}});
async function user(req:Request){const a=req.headers.get("Authorization");if(!a?.startsWith("Bearer "))return null;const c=createClient(SUPABASE_URL,ANON_KEY,{global:{headers:{Authorization:a}},auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await c.auth.getUser();return error||!data.user?null:data.user;}
async function refresh(c:any){if(!XERO_CLIENT_ID||!XERO_CLIENT_SECRET)throw new Error("Xero credentials are not configured in Supabase.");if(c.access_token_expires_at&&Date.parse(c.access_token_expires_at)>Date.now()+120000)return c;if(!c.refresh_token)throw new Error("The Xero connection needs to be reauthorised.");const r=await fetch("https://identity.xero.com/connect/token",{method:"POST",headers:{Authorization:`Basic ${btoa(`${XERO_CLIENT_ID}:${XERO_CLIENT_SECRET}`)}`,"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:c.refresh_token}).toString()});const t=await r.json().catch(()=>({}));if(!r.ok)throw new Error(t.error_description||t.error||"Xero token refresh failed.");const u={access_token:t.access_token,refresh_token:t.refresh_token||c.refresh_token,access_token_expires_at:new Date(Date.now()+Number(t.expires_in||1800)*1000).toISOString(),refresh_token_expires_at:new Date(Date.now()+60*86400000).toISOString(),updated_at:new Date().toISOString()};const s=await db(`xero_connections?user_id=eq.${encodeURIComponent(c.user_id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify(u)});if(!s.ok)throw new Error("Could not save refreshed Xero tokens.");return {...c,...u};}
async function connection(userId:string){const r=await db(`xero_connections?user_id=eq.${encodeURIComponent(userId)}&select=*`);const rows=await r.json().catch(()=>[]);if(!r.ok||!rows?.[0])throw new Error("Xero is not connected.");return refresh(rows[0]);}
async function xero(c:any,path:string,init:RequestInit={}){const r=await fetch(`${XERO_API}${path}`,{...init,headers:{Authorization:`Bearer ${c.access_token}`,"Xero-tenant-id":c.tenant_id,Accept:"application/json","Content-Type":"application/json",...(init.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok){const v=b?.Elements?.flatMap((e:any)=>e?.ValidationErrors||[])?.map((e:any)=>e.Message).filter(Boolean)||[];throw new Error(v.join("; ")||b?.Message||b?.Detail||`Xero API error ${r.status}`);}return b;}
async function companyId(userId:string){const m=await db(`company_members?user_id=eq.${encodeURIComponent(userId)}&status=eq.active&select=company_id&limit=1`);const ms=await m.json().catch(()=>[]);if(ms?.[0]?.company_id)return ms[0].company_id;const o=await db(`companies?owner_id=eq.${encodeURIComponent(userId)}&select=id&limit=1`);const cs=await o.json().catch(()=>[]);return cs?.[0]?.id||null;}
const filter=(cid:string|null,userId:string)=>cid?`company_id=eq.${encodeURIComponent(cid)}`:`user_id=eq.${encodeURIComponent(userId)}`;
async function syncCustomer(c:any,customer:any){let id=customer.xero_contact_id;if(!id){const field=customer.email?"EmailAddress":"Name";const value=String(customer.email||customer.name).replace(/"/g,'\\"');const r=await xero(c,`/Contacts?where=${encodeURIComponent(`${field}=="${value}"`)}&pageSize=1`);id=r?.Contacts?.[0]?.ContactID;}const payload={Contacts:[{...(id?{ContactID:id}:{}),Name:String(customer.name||"Customer").trim().replace(/\s+/g," ").slice(0,255),...(customer.email?{EmailAddress:customer.email}:{}),...(customer.phone?{Phones:[{PhoneType:"DEFAULT",PhoneNumber:customer.phone}]}:{}),...(customer.address_line1||customer.city||customer.postcode?{Addresses:[{AddressType:"STREET",AddressLine1:customer.address_line1||undefined,AddressLine2:customer.address_line2||undefined,City:customer.city||undefined,Region:customer.address_region||undefined,PostalCode:customer.postcode||undefined,Country:customer.address_country_code||undefined}]}:{})}]};const r=await xero(c,"/Contacts",{method:"POST",body:JSON.stringify(payload)});const contact=r?.Contacts?.[0];if(!contact?.ContactID)throw new Error(`Xero did not return a contact ID for ${customer.name}.`);await db(`customers?id=eq.${encodeURIComponent(customer.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({xero_contact_id:contact.ContactID})});return contact;}
function taxPart(t:number,s:number,a:number){return !t||!s?0:Number((t*(a/s)).toFixed(2));}
async function syncInvoice(c:any,invoice:any,items:any[],customer:any){let cid=customer.xero_contact_id;if(!cid)cid=(await syncCustomer(c,customer)).ContactID;const cr=await xero(c,`/Contacts/${encodeURIComponent(cid)}`);const contact=cr?.Contacts?.[0];const accountCode=contact?.SalesDefaultAccountCode;if(!accountCode)throw new Error(`Xero customer ${customer.name} has no default sales account code. Set a Sales Account on the Xero contact and sync again.`);let iid=invoice.xero_invoice_id;if(!iid){const q=await xero(c,`/Invoices?InvoiceNumber=${encodeURIComponent(invoice.invoice_number||"")}&pageSize=1`);iid=q?.Invoices?.[0]?.InvoiceID;}const source=items.length?items:[{description:invoice.description||invoice.invoice_number||"JobPilot invoice",quantity:1,unit_price:Number(invoice.subtotal||invoice.total||0)}];const sub=Number(invoice.subtotal||0),vat=Number(invoice.vat||0);const lines=source.map((i:any)=>{const q=Number(i.quantity||1),u=Number(i.unit_price||0),a=Number(i.total??q*u);return {Description:String(i.description||"Service").slice(0,4000),Quantity:q,UnitAmount:u,AccountCode:accountCode,...(vat?{TaxAmount:taxPart(vat,sub||a,a)}:{})};});const payload={...(iid?{InvoiceID:iid}:{}),Type:"ACCREC",Contact:{ContactID:cid},InvoiceNumber:invoice.invoice_number||undefined,Date:invoice.issue_date||undefined,DueDate:invoice.due_date||undefined,Status:"AUTHORISED",LineAmountTypes:vat?"Exclusive":"NoTax",LineItems:lines};const result=await xero(c,"/Invoices",{method:"POST",body:JSON.stringify({Invoices:[payload]})});const remote=result?.Invoices?.[0];if(!remote?.InvoiceID)throw new Error(`Xero did not return an invoice ID for ${invoice.invoice_number}.`);await db(`invoices?id=eq.${encodeURIComponent(invoice.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({xero_invoice_id:remote.InvoiceID,xero_sync_status:"synced",xero_sync_error:null,xero_synced_at:new Date().toISOString()})});return remote;}
async function payments(c:any,userId:string,cid:string|null){const r=await db(`invoices?${filter(cid,userId)}&xero_invoice_id=not.is.null&select=id,xero_invoice_id,status`);const rows=await r.json().catch(()=>[]);if(!r.ok)throw new Error("Could not load synced invoices.");let updated=0;for(const i of rows){try{const b=await xero(c,`/Invoices/${encodeURIComponent(i.xero_invoice_id)}`);const v=b?.Invoices?.[0];if(v&&Number(v.AmountDue||0)<=0.005&&i.status!=="paid"){await db(`invoices?id=eq.${encodeURIComponent(i.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"paid",paid_date:v.FullyPaidOnDate||new Date().toISOString().slice(0,10)})});updated++;}}catch(e){console.error("Xero payment sync",i.id,e);}}return updated;}
async function syncAll(c:any,userId:string,cid:string|null){const f=filter(cid,userId);const cr=await db(`customers?${f}&select=*`);const customers=await cr.json().catch(()=>[]);if(!cr.ok)throw new Error("Could not load JobPilot customers.");let customersSynced=0,customerErrors=0;for(const customer of customers){try{await syncCustomer(c,customer);customersSynced++;}catch(e){customerErrors++;console.error("Xero customer sync",customer.id,e);}}const ir=await db(`invoices?${f}&select=*`);const invoices=await ir.json().catch(()=>[]);if(!ir.ok)throw new Error("Could not load JobPilot invoices.");const map=new Map(customers.map((x:any)=>[x.id,x]));let invoicesSynced=0,invoiceErrors=0;for(const invoice of invoices){const customer=map.get(invoice.customer_id);if(!customer){invoiceErrors++;continue;}try{const itemsR=await db(`invoice_items?invoice_id=eq.${encodeURIComponent(invoice.id)}&select=*`);const items=await itemsR.json().catch(()=>[]);await syncInvoice(c,invoice,Array.isArray(items)?items:[],customer);invoicesSynced++;}catch(e){invoiceErrors++;await db(`invoices?id=eq.${encodeURIComponent(invoice.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({xero_sync_status:"error",xero_sync_error:e instanceof Error?e.message:String(e),xero_synced_at:new Date().toISOString()})});}}const paymentsUpdated=await payments(c,userId,cid);return {customersSynced,customerErrors,invoicesSynced,invoiceErrors,paymentsUpdated};}
Deno.serve(async(req:Request)=>{try{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});const u=await user(req);if(!u)return json({error:"Missing or invalid authorization."},401);const c=await connection(u.id),cid=await companyId(u.id),body=await req.json().catch(()=>({}));if(String(body.action||"sync").toLowerCase()==="payments")return json({ok:true,paymentsUpdated:await payments(c,u.id,cid)});return json({ok:true,...await syncAll(c,u.id,cid)});}catch(e){return json({error:e instanceof Error?e.message:"Unexpected Xero sync error."},500);}});
