import { supabase } from "../supabase.js";

const JOBPILOT_ADMIN_ID = "9a89bdf0-1f17-48ec-a622-db59545e8ada";
const PLANS = { solo: { label: "Solo", price: 7.49 }, team: { label: "Team", price: 24.99 }, business: { label: "Business", price: 59.99 }, pro: { label: "Pro", price: 99.99 } };

function escapeHtml(value) { return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#039;"); }
function money(value) { return `£${Number(value || 0).toFixed(2)}`; }
function statusFor(company, subscription) { const status = String(subscription?.status || company?.billing_status || "pending").toLowerCase(); if (["active", "trialing"].includes(status)) return "active"; if (["past_due", "unpaid"].includes(status)) return "at risk"; if (["canceled", "incomplete_expired"].includes(status)) return "cancelled"; return status || "pending"; }
function monthlyValue(company, subscription) { const plan = String(subscription?.plan || company?.plan || "solo").toLowerCase(); return Number(PLANS[plan]?.price || 0); }
async function isSuperUser() { const { data: { user } = {} } = await supabase.auth.getUser(); return String(user?.id || "") === JOBPILOT_ADMIN_ID; }

async function loadData() {
  const [{ data: promoters, error: e1 }, { data: referrals, error: e2 }, { data: companies, error: e3 }, { data: subscriptions, error: e4 }] = await Promise.all([
    supabase.from("referral_promoters").select("*").order("created_at", { ascending: false }),
    supabase.from("referrals").select("*").order("created_at", { ascending: false }),
    supabase.from("companies").select("id,name,plan,billing_status,stripe_customer_id"),
    supabase.from("company_subscriptions").select("company_id,plan,status,current_period_end,cancel_at_period_end")
  ]);
  const error = e1 || e2 || e3 || e4; if (error) throw error;
  return { promoters: promoters || [], referrals: referrals || [], companies: companies || [], subscriptions: subscriptions || [] };
}

function renderSummary(container, promoters, rows, onPromotersClick) {
  const active = rows.filter(r => r.status === "active");
  const mrr = active.reduce((sum, r) => sum + r.value, 0);
  const commission = active.reduce((sum, r) => sum + r.commission, 0);
  if (!document.getElementById("jobpilot-referral-stats-style")) {
    const style = document.createElement("style");
    style.id = "jobpilot-referral-stats-style";
    style.textContent = ".referral-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.referral-stats .stat-card{min-width:0}.referral-stats .stat-card.clickable{cursor:pointer;transition:transform .15s ease,box-shadow .15s ease}.referral-stats .stat-card.clickable:hover{transform:translateY(-1px);box-shadow:0 4px 14px rgba(0,0,0,.08)}@media(max-width:900px){.referral-stats{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.referral-stats{grid-template-columns:1fr}}";
    document.head.appendChild(style);
  }
  container.innerHTML = `<div class="referral-stats"><div class="stat-card clickable" id="referral-promoters-stat" role="button" tabindex="0" title="View promoter statistics"><div class="stat-icon">👤</div><div><span>Promoters</span><strong>${promoters.length}</strong></div></div><div class="stat-card"><div class="stat-icon">↗</div><div><span>Referrals</span><strong>${rows.length}</strong></div></div><div class="stat-card"><div class="stat-icon">✓</div><div><span>Active subscribers</span><strong>${active.length}</strong></div></div><div class="stat-card"><div class="stat-icon">£</div><div><span>Monthly commission</span><strong>${money(commission)}</strong></div></div></div><div class="panel" style="margin-bottom:18px;"><div class="panel-header"><div><h2>Referral MRR</h2><p>Current monthly subscription revenue generated by promoters</p></div><strong style="font-size:24px;">${money(mrr)}</strong></div></div>`;
  const card = document.getElementById("referral-promoters-stat");
  card?.addEventListener("click", onPromotersClick);
  card?.addEventListener("keydown", event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onPromotersClick?.(); } });
}

function renderPromoters(container, promoters, rows, onSelectPromoter) {
  const statsByPromoter = new Map();
  rows.forEach(row => {
    const current = statsByPromoter.get(row.promoterId) || { referrals: 0, active: 0, atRisk: 0, cancelled: 0, mrr: 0, commission: 0 };
    current.referrals += 1;
    if (row.status === "active") { current.active += 1; current.mrr += row.value; current.commission += row.commission; }
    else if (row.status === "at risk") current.atRisk += 1;
    else if (row.status === "cancelled") current.cancelled += 1;
    statsByPromoter.set(row.promoterId, current);
  });

  container.innerHTML = `<div class="page-actions"><div><h2>Promoters</h2><p>Click a promoter to view their referrals, subscribers and commission.</p></div><button id="referral-add-promoter" class="button primary" type="button">+ Add Promoter</button></div><div class="panel"><div class="table-container"><table><thead><tr><th>Promoter</th><th>Referrals</th><th>Active</th><th>MRR</th><th>Commission / month</th><th>Status</th><th>Actions</th></tr></thead><tbody>${promoters.map(p => { const s = statsByPromoter.get(p.id) || { referrals: 0, active: 0, atRisk: 0, cancelled: 0, mrr: 0, commission: 0 }; return `<tr class="referral-promoter-row" data-view-promoter="${escapeHtml(p.id)}" style="cursor:pointer"><td><strong>${escapeHtml(p.name)}</strong><div class="muted">${escapeHtml(p.email || "")}</div></td><td>${s.referrals}</td><td>${s.active}</td><td>${money(s.mrr)}</td><td>${money(s.commission)}</td><td>${p.active ? "Active" : "Inactive"}</td><td><button type="button" class="secondary-btn" data-edit-promoter="${escapeHtml(p.id)}">Edit</button> <button type="button" class="secondary-btn" data-toggle-promoter="${escapeHtml(p.id)}">${p.active ? "Disable" : "Enable"}</button></td></tr>`; }).join("") || `<tr><td colspan="7">No promoters yet.</td></tr>`}</tbody></table></div></div>`;

  document.getElementById("referral-add-promoter")?.addEventListener("click", async () => {
    const name = window.prompt("Promoter name:"); if (!name?.trim()) return;
    const code = window.prompt("Referral code:", name.trim().replace(/[^a-z0-9]+/gi, "").toUpperCase()); if (!code?.trim()) return;
    const commission = Number(window.prompt("Commission percentage:", "30")); if (!Number.isFinite(commission) || commission < 0 || commission > 100) return alert("Enter a commission between 0 and 100.");
    const email = window.prompt("Promoter email (optional):") || null;
    const { error } = await supabase.from("referral_promoters").insert({ name: name.trim(), code: code.trim().toUpperCase(), commission_percent: commission, email });
    if (error) return alert(error.message); await renderReferralsPage();
  });

  container.querySelectorAll("[data-view-promoter]").forEach(row => row.addEventListener("click", event => { if (event.target.closest("button")) return; onSelectPromoter?.(row.getAttribute("data-view-promoter")); }));
  container.querySelectorAll("[data-edit-promoter]").forEach(button => button.addEventListener("click", async () => {
    const id = button.getAttribute("data-edit-promoter"); const promoter = promoters.find(p => p.id === id); if (!promoter) return;
    const name = window.prompt("Promoter name:", promoter.name || ""); if (!name?.trim()) return;
    const code = window.prompt("Referral code:", promoter.code || ""); if (!code?.trim()) return;
    const commission = Number(window.prompt("Commission percentage:", String(promoter.commission_percent ?? 30))); if (!Number.isFinite(commission) || commission < 0 || commission > 100) return alert("Enter a commission between 0 and 100.");
    const emailInput = window.prompt("Promoter email (optional):", promoter.email || ""); const email = emailInput?.trim() || null;
    const { error } = await supabase.from("referral_promoters").update({ name: name.trim(), code: code.trim().toUpperCase(), commission_percent: commission, email, updated_at: new Date().toISOString() }).eq("id", id);
    if (error) return alert(error.message); await renderReferralsPage();
  }));
  container.querySelectorAll("[data-toggle-promoter]").forEach(button => button.addEventListener("click", async () => { const id = button.getAttribute("data-toggle-promoter"); const promoter = promoters.find(p => p.id === id); if (!promoter) return; const { error } = await supabase.from("referral_promoters").update({ active: !promoter.active, updated_at: new Date().toISOString() }).eq("id", id); if (error) return alert(error.message); await renderReferralsPage(); }));
}

function renderPromoterDetail(container, promoter, rows, onBack) {
  const active = rows.filter(r => r.status === "active");
  const atRisk = rows.filter(r => r.status === "at risk");
  const cancelled = rows.filter(r => r.status === "cancelled");
  const mrr = active.reduce((sum, r) => sum + r.value, 0);
  const commission = active.reduce((sum, r) => sum + r.commission, 0);
  const referralLink = `${window.location.origin}/?ref=${encodeURIComponent(promoter.code)}`;
  const conversion = rows.length ? (active.length / rows.length) * 100 : 0;

  container.innerHTML = `<div class="page-actions"><div><h2>${escapeHtml(promoter.name)}</h2><p>Promoter statistics and referred customers.</p></div><button id="promoter-detail-back" class="button secondary" type="button">← Back to Promoters</button></div><div class="panel" style="margin-bottom:18px;"><div class="panel-header"><div><h3>Referral link</h3><p>Share this link with customers to attribute new signups.</p></div><input readonly value="${escapeHtml(referralLink)}" style="min-width:320px;max-width:100%;"></div><div style="margin-top:8px;"><strong>Code:</strong> <code>${escapeHtml(promoter.code)}</code> &nbsp; <strong>Commission:</strong> ${Number(promoter.commission_percent).toFixed(0)}% &nbsp; <strong>Status:</strong> ${promoter.active ? "Active" : "Inactive"}</div></div><div class="referral-detail-stats" style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin-bottom:18px;"><div class="stat-card"><div><span>Total referrals</span><strong>${rows.length}</strong></div></div><div class="stat-card"><div><span>Active subscribers</span><strong>${active.length}</strong></div></div><div class="stat-card"><div><span>Referral MRR</span><strong>${money(mrr)}</strong></div></div><div class="stat-card"><div><span>Monthly commission</span><strong>${money(commission)}</strong></div></div></div><div class="panel" style="margin-bottom:18px;"><div class="panel-header"><div><h3>Performance</h3><p>Current status of customers attributed to this promoter.</p></div><div><strong>${conversion.toFixed(1)}%</strong> active conversion</div></div><div style="display:flex;gap:24px;flex-wrap:wrap;margin-top:12px;"><span><strong>${active.length}</strong> Active</span><span><strong>${atRisk.length}</strong> At risk</span><span><strong>${cancelled.length}</strong> Cancelled</span></div></div><div class="panel"><div class="panel-header"><div><h3>Referred customers</h3><p>Customers currently attributed to ${escapeHtml(promoter.name)}.</p></div></div><div class="table-container"><table><thead><tr><th>Company</th><th>Plan</th><th>Status</th><th>Monthly value</th><th>Commission</th></tr></thead><tbody>${rows.map(r => `<tr><td>${escapeHtml(r.companyName || "Unknown company")}</td><td>${escapeHtml(r.planLabel)}</td><td><strong>${escapeHtml(r.status)}</strong>${r.cancelAtPeriodEnd && r.periodEnd ? `<div class="muted">Ends ${escapeHtml(new Date(r.periodEnd).toLocaleDateString())}</div>` : ""}</td><td>${money(r.value)}</td><td>${money(r.commission)}/mo</td></tr>`).join("") || `<tr><td colspan="5">No referrals for this promoter yet.</td></tr>`}</tbody></table></div></div>`;
  document.getElementById("promoter-detail-back")?.addEventListener("click", onBack);
}

function renderReferralRows(container, rows) {
  container.innerHTML = `<div class="panel"><div class="panel-header"><div><h2>Referral Customers</h2><p>Live subscription status and recurring commission.</p></div></div><div class="table-container"><table><thead><tr><th>Promoter</th><th>Company</th><th>Plan</th><th>Status</th><th>Monthly value</th><th>Commission</th></tr></thead><tbody>${rows.map(r => `<tr><td>${escapeHtml(r.promoter)}</td><td>${escapeHtml(r.companyName || "Unknown company")}</td><td>${escapeHtml(r.planLabel)}</td><td><strong>${escapeHtml(r.status)}</strong>${r.cancelAtPeriodEnd && r.periodEnd ? `<div class="muted">Ends ${escapeHtml(new Date(r.periodEnd).toLocaleDateString())}</div>` : ""}</td><td>${money(r.value)}</td><td>${money(r.commission)}/mo</td></tr>`).join("") || `<tr><td colspan="6">No referrals yet.</td></tr>`}</tbody></table></div></div>`;
}

export async function renderReferralsPage() {
  if (!(await isSuperUser())) { alert("You do not have permission to view referrals."); return; }
  const content = document.getElementById("pageContent"); if (!content) return;
  document.getElementById("pageTitle").textContent = "Referrals";
  document.getElementById("pageSubtitle").textContent = "Manage JobPilot referral partners and recurring commission.";
  document.querySelectorAll(".nav-item").forEach(item => item.classList.remove("active")); document.getElementById("jobpilot-management-button")?.classList.add("active");
  content.innerHTML = `<div class="page-actions"><div><h2>Referrals</h2><p>Super User referral management.</p></div><button id="referrals-back" class="button secondary" type="button">← Back to Management</button></div><div id="referral-summary"></div><div id="referral-promoters" style="display:none;"></div><div id="referral-customers" style="margin-top:18px;"></div>`;
  document.getElementById("referrals-back")?.addEventListener("click", () => window.renderManagementPage?.());
  try {
    const { promoters, referrals, companies, subscriptions } = await loadData();
    const promoterMap = new Map(promoters.map(p => [p.id, p]));
    const companyMap = new Map(companies.map(c => [c.id, c]));
    const subscriptionMap = new Map(subscriptions.map(s => [s.company_id, s]));
    const rows = referrals.map(ref => {
      const company = companyMap.get(ref.company_id) || {};
      const subscription = subscriptionMap.get(ref.company_id) || {};
      const plan = String(subscription.plan || company.plan || ref.plan || "solo").toLowerCase();
      const value = monthlyValue(company, subscription);
      const percent = Number(ref.commission_percent || promoterMap.get(ref.promoter_id)?.commission_percent || 30);
      const status = statusFor(company, subscription);
      return { promoter: promoterMap.get(ref.promoter_id)?.name || "Unknown", promoterId: ref.promoter_id, companyName: company.name, planLabel: PLANS[plan]?.label || plan, status, value, commission: ["active", "at risk"].includes(status) ? value * percent / 100 : 0, cancelAtPeriodEnd: subscription.cancel_at_period_end === true, periodEnd: subscription.current_period_end, updatedAt: ref.updated_at || ref.created_at };
    });

    const summary = document.getElementById("referral-summary");
    const promotersPanel = document.getElementById("referral-promoters");
    const customersPanel = document.getElementById("referral-customers");

    const showPromoters = () => {
      summary.style.display = "none";
      customersPanel.style.display = "none";
      promotersPanel.style.display = "block";
      renderPromoters(promotersPanel, promoters, rows, showPromoterDetail);
    };

    const showPromoterDetail = promoterId => {
      const promoter = promoters.find(p => p.id === promoterId); if (!promoter) return;
      summary.style.display = "none";
      customersPanel.style.display = "none";
      promotersPanel.style.display = "block";
      renderPromoterDetail(promotersPanel, promoter, rows.filter(r => r.promoterId === promoterId), showPromoters);
    };

    renderSummary(summary, promoters, rows, showPromoters);
    renderReferralRows(customersPanel, rows);
  } catch (error) { console.error("JobPilot referrals:", error); content.innerHTML += `<div class="panel"><h3>Could not load referrals</h3><p>${escapeHtml(error.message || "Unable to load referral data.")}</p></div>`; }
}

window.renderReferralsPage = renderReferralsPage;
