import { supabase } from "../supabase.js";

const JOBPILOT_ADMIN_ID = "9a89bdf0-1f17-48ec-a622-db59545e8ada";
const PLANS = { solo: { label: "Solo", price: 7.49 }, team: { label: "Team", price: 24.99 }, business: { label: "Business", price: 59.99 }, pro: { label: "Pro", price: 99.99 } };

function escapeHtml(value) { return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#039;"); }
function money(value) { return `£${Number(value || 0).toFixed(2)}`; }
function statusFor(company, subscription) { const status = String(subscription?.status || company?.billing_status || "pending").toLowerCase(); if (["active", "trialing"].includes(status)) return "active"; if (["past_due", "unpaid"].includes(status)) return "at risk"; if (["canceled", "incomplete_expired"].includes(status)) return "cancelled"; return status || "pending"; }
function monthlyValue(company, subscription) { const plan = String(subscription?.plan || company?.plan || "solo").toLowerCase(); return Number(PLANS[plan]?.price || 0); }
async function isSuperUser() { const { data: { user } = {} } = await supabase.auth.getUser(); return String(user?.id || "") === JOBPILOT_ADMIN_ID; }

async function loadData() {
  const [{ data: promoters, error: e1 }, { data: referrals, error: e2 }, { data: companies, error: e3 }, { data: subscriptions, error: e4 }] = await Promise.all([
    supabase.from("referral_promoters").select("*").order("created_at", { ascending: false }),
    supabase.from("referrals").select("*").order("created_at", { ascending: false }),
    supabase.from("companies").select("id,name,plan,billing_status,stripe_customer_id"),
    supabase.from("company_subscriptions").select("company_id,plan,status,current_period_end,cancel_at_period_end")
  ]);
  const error = e1 || e2 || e3 || e4; if (error) throw error;
  return { promoters: promoters || [], referrals: referrals || [], companies: companies || [], subscriptions: subscriptions || [] };
}

function renderSummary(container, rows) {
  const active = rows.filter(r => r.status === "active");
  const mrr = active.reduce((sum, r) => sum + r.value, 0);
  const commission = active.reduce((sum, r) => sum + r.commission, 0);
  container.innerHTML = `<div class="stats"><div class="stat-card"><div class="stat-icon">👤</div><div><span>Promoters</span><strong>${new Set(rows.map(r => r.promoterId)).size}</strong></div></div><div class="stat-card"><div class="stat-icon">↗</div><div><span>Referrals</span><strong>${rows.length}</strong></div></div><div class="stat-card"><div class="stat-icon">✓</div><div><span>Active subscribers</span><strong>${active.length}</strong></div></div><div class="stat-card"><div class="stat-icon">£</div><div><span>Monthly commission</span><strong>${money(commission)}</strong></div></div></div><div class="panel" style="margin-bottom:18px;"><div class="panel-header"><div><h2>Referral MRR</h2><p>Current monthly subscription revenue generated by promoters</p></div><strong style="font-size:24px;">${money(mrr)}</strong></div></div>`;
}

function renderPromoters(container, promoters) {
  const base = window.location.origin;
  container.innerHTML = `<div class="page-actions"><div><h2>Promoters</h2><p>Create and manage referral partners.</p></div><button id="referral-add-promoter" class="button primary" type="button">+ Add Promoter</button></div><div class="panel"><div class="table-container"><table><thead><tr><th>Name</th><th>Code</th><th>Commission</th><th>Referral link</th><th>Status</th><th></th></tr></thead><tbody>${promoters.map(p => `<tr><td><strong>${escapeHtml(p.name)}</strong><div class="muted">${escapeHtml(p.email || "")}</div></td><td><code>${escapeHtml(p.code)}</code></td><td>${Number(p.commission_percent).toFixed(0)}%</td><td><input readonly value="${escapeHtml(`${base}/?ref=${encodeURIComponent(p.code)}`)}" style="min-width:260px;"></td><td>${p.active ? "Active" : "Inactive"}</td><td><button type="button" class="secondary-btn" data-toggle-promoter="${escapeHtml(p.id)}">${p.active ? "Disable" : "Enable"}</button></td></tr>`).join("") || `<tr><td colspan="6">No promoters yet.</td></tr>`}</tbody></table></div></div>`;

  document.getElementById("referral-add-promoter")?.addEventListener("click", async () => {
    const name = window.prompt("Promoter name:"); if (!name?.trim()) return;
    const code = window.prompt("Referral code:", name.trim().replace(/[^a-z0-9]+/gi, "").toUpperCase()); if (!code?.trim()) return;
    const commission = Number(window.prompt("Commission percentage:", "30")); if (!Number.isFinite(commission) || commission < 0 || commission > 100) return alert("Enter a commission between 0 and 100.");
    const email = window.prompt("Promoter email (optional):") || null;
    const { error } = await supabase.from("referral_promoters").insert({ name: name.trim(), code: code.trim().toUpperCase(), commission_percent: commission, email });
    if (error) return alert(error.message); await renderReferralsPage();
  });
  container.querySelectorAll("[data-toggle-promoter]").forEach(button => button.addEventListener("click", async () => { const id = button.getAttribute("data-toggle-promoter"); const promoter = promoters.find(p => p.id === id); if (!promoter) return; const { error } = await supabase.from("referral_promoters").update({ active: !promoter.active, updated_at: new Date().toISOString() }).eq("id", id); if (error) return alert(error.message); await renderReferralsPage(); }));
}

function renderReferralRows(container, rows) {
  container.innerHTML = `<div class="panel"><div class="panel-header"><div><h2>Referral Customers</h2><p>Live subscription status and recurring commission.</p></div></div><div class="table-container"><table><thead><tr><th>Promoter</th><th>Company</th><th>Plan</th><th>Status</th><th>Monthly value</th><th>Commission</th></tr></thead><tbody>${rows.map(r => `<tr><td>${escapeHtml(r.promoter)}</td><td>${escapeHtml(r.companyName || "Unknown company")}</td><td>${escapeHtml(r.planLabel)}</td><td><strong>${escapeHtml(r.status)}</strong>${r.cancelAtPeriodEnd && r.periodEnd ? `<div class="muted">Ends ${escapeHtml(new Date(r.periodEnd).toLocaleDateString())}</div>` : ""}</td><td>${money(r.value)}</td><td>${money(r.commission)}/mo</td></tr>`).join("") || `<tr><td colspan="6">No referrals yet.</td></tr>`}</tbody></table></div></div>`;
}

export async function renderReferralsPage() {
  if (!(await isSuperUser())) { alert("You do not have permission to view referrals."); return; }
  const content = document.getElementById("pageContent"); if (!content) return;
  document.getElementById("pageTitle").textContent = "Referrals";
  document.getElementById("pageSubtitle").textContent = "Manage JobPilot referral partners and recurring commission.";
  document.querySelectorAll(".nav-item").forEach(item => item.classList.remove("active")); document.getElementById("jobpilot-management-button")?.classList.add("active");
  content.innerHTML = `<div class="page-actions"><div><h2>Referrals</h2><p>Super User referral management.</p></div><button id="referrals-back" class="button secondary" type="button">← Back to Management</button></div><div id="referral-summary"></div><div id="referral-promoters"></div><div id="referral-customers" style="margin-top:18px;"></div>`;
  document.getElementById("referrals-back")?.addEventListener("click", () => window.renderManagementPage?.());
  try {
    const { promoters, referrals, companies, subscriptions } = await loadData();
    const promoterMap = new Map(promoters.map(p => [p.id, p])); const companyMap = new Map(companies.map(c => [c.id, c])); const subscriptionMap = new Map(subscriptions.map(s => [s.company_id, s]));
    const rows = referrals.map(ref => { const company = companyMap.get(ref.company_id) || {}; const subscription = subscriptionMap.get(ref.company_id) || {}; const plan = String(subscription.plan || company.plan || ref.plan || "solo").toLowerCase(); const value = monthlyValue(company, subscription); const percent = Number(ref.commission_percent || promoterMap.get(ref.promoter_id)?.commission_percent || 30); const status = statusFor(company, subscription); return { promoter: promoterMap.get(ref.promoter_id)?.name || "Unknown", promoterId: ref.promoter_id, companyName: company.name, planLabel: PLANS[plan]?.label || plan, status, value, commission: ["active", "at risk"].includes(status) ? value * percent / 100 : 0, cancelAtPeriodEnd: subscription.cancel_at_period_end === true, periodEnd: subscription.current_period_end, updatedAt: ref.updated_at || ref.created_at }; });
    renderSummary(document.getElementById("referral-summary"), rows); renderPromoters(document.getElementById("referral-promoters"), promoters); renderReferralRows(document.getElementById("referral-customers"), rows);
  } catch (error) { console.error("JobPilot referrals:", error); content.innerHTML += `<div class="panel"><h3>Could not load referrals</h3><p>${escapeHtml(error.message || "Unable to load referral data.")}</p></div>`; }
}

window.renderReferralsPage = renderReferralsPage;
